### ISSUE TITLE
configure doesn't complain about missing libfcgi-dev

### ISSUE THREAD

**Issue by gravitystorm** [zerebubuth/openstreetmap-cgimap#100]
I've just been not-carefully-following the installation instructions, but `./configure --with-fcgi=/usr` worked and generated the makefile, and make then failed with 

```
fcgi_request.cpp:7:21: fatal error: fcgiapp.h: No such file or directory
 #include <fcgiapp.h>
```

configure should probably have complained that libfcgi-dev wasn't installed.

**Comment by zerebubuth** [comment]
I've added a new, better configure macro for this which actually gives an error message when it can't find the headers or libraries. So the error should appear at configure time with an appropriate complaint about installing `libfcgi-dev` rather than silently failing.
