### ISSUE TITLE
Dual ABI problems with boost / pqxx

### ISSUE THREAD

**Issue by zerebubuth** [zerebubuth/openstreetmap-cgimap#103]
On Ubuntu 15.10, the [GCC dual ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) is present. Sadly, the Boost libraries appear to be compiled with the new ABI and the PQXX ones without, which means they have mutually incomprehensible `std::string` implementations.

There's probably some way to work around this, but I can't figure it out right now.

**Comment by tomhughes** [comment]
I really don't think there is, which is why any sane distribution does a full rebuild when updating gcc to one that uses the new ABI...

**Comment by zerebubuth** [comment]
I don't have this in 16.04 any more. Tempted to avoid fixing, unless it's really necessary. Please ask for a re-open on this ticket with your platform & distribution details if you experience this issue.
