### ISSUE TITLE
ERROR:Could not convert string to unsigned integer

### ISSUE THREAD

**Issue by frankxu2004** [zerebubuth/openstreetmap-cgimap#105]
After dumping the data dump using the osmosis tool int the database on my server, all queries to the API recieved error message: 
`<osm version="0.6" generator="CGImap 0.4.0 (30216 galaxy)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<bounds minlat="31.2310779" minlon="121.5241742" maxlat="31.2369124" maxlon="121.5585065" />
<error>Could not convert string to unsigned integer: '-1'</error>
</osm>
`
I am not really sure that happened, after a quick search I thought that  I have been fixed previously due to anomynous users handling.

**Comment by zerebubuth** [comment]
The anonymous user handling was fixed in a previous version of cgimap, but I think Osmosis creates a "special" anonymous user with an ID of -1 when it loads a dump with anonymous data in it. Please could you check to see if you have only one anonymous user with an ID of -1, and that all the other IDs (e.g: changesets) all have positive IDs? If so, then I could implement a simple work-around.

**Comment by pnorman** [comment]
I've used an osmosis-loaded database before, so I believe this *used* to work

**Comment by frankxu2004** [comment]
After checking my database, my ‘changesets’ table have two rows, 
```
0	-1	2016-03-06 23:19:56.845220	-900000000	900000000	-1800000000	1800000000	2016-03-06 23:19:56.845220	0
-1	-1	2016-03-06 23:19:56.845220	-900000000	900000000	-1800000000	1800000000	2016-03-06 23:19:56.845220	0
```
That is, id is 0 and -1, user_id is -1. Not sure why there are two rows though.

In my other tables like nodes, ways, way_nodes, etc., all data are with a changeset_id of -1.

Any more information that I could provide to help this issue? Thanks

**Comment by zerebubuth** [comment]
Thanks!

It looks like we've seen the negative user ID problem, and [fixed that](https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/backend/apidb/changeset.cpp#L33-L35), but I'm not sure why there's a negative changeset ID, as changeset IDs are available even when the change was anonymous. I wonder if there's some interaction with the [PBF2 Osmosis module](https://github.com/openstreetmap/osmosis/blob/master/osmosis-pbf2/src/main/java/org/openstreetmap/osmosis/pbf2/v0_6/impl/PbfBlobDecoder.java#L58), which seems like it might possibly output a changeset with ID -1.

Should be easy enough to fix - I might just have to go through and break out the `changeset_id_t` separate from `osm_id_t`.

**Comment by frankxu2004** [comment]
Thanks!

I think that you may have the point here. I do use the dumped PBF file format to populate my own database with Osmosis, so maybe changeset_id = -1 is possible.

**Comment by frankxu2004** [comment]
Is there anything I could do to resolve this issue? I'm aware that all ids are osm_id_t but how to separate that type for changeset_id or make explicit if-else in logic. I'm still not familiar with how the whole data goes through.
