### ISSUE TITLE
Windows EXE needed

### ISSUE THREAD

**Issue by ehx-v1** [zerebubuth/openstreetmap-cgimap#108]
The problem is the following: I need to generate OSM from existing data in Java, because Neo4j Spatial has its OSM generated by CGIMap 0.0.2. Which means, it would be extremely unpractical having to call `System.exec("<path_to_Cygwin>/Cygwin.exe")` because the user would have to insert the command. That's why I need an EXE of this OSM generator I can run on Windows with `System.exec("CGImap.exe", <necessary_parameters>)`, so I can generate the parameters in code from the data I have and then pass the generated OSM to the Neo4j Spatial OSMImporter.
The use of Neo4j Spatial is an upcoming trend in map-related applications, so I suppose this will be a general requirement quite soon.

**Comment by pnorman** [comment]
cgimap is designed to interface with a database in the apidb schema for specific OSM API calls in a high volume production environment. It doesn't interface with java, so you'd have to set up a database, load the data into it, and then use cgimap.

Your java code would also need to talk fcgi to send requests to cgimap.

Given that serializing OSM XML is fairly easy and there are certainly better suited libraries, I wouldn't suggest using cgimap, which does not do what you appear to want.

**Comment by ehx-v1** [comment]
So CGImap is not responsible for the specific format Neo4j Spatial uses?
Because from what I know, OSM is no full standard, and there are probably some particular details the Neo4j Spatial importer needs for recognizing the OSM at all. These details need to be manually set?
I had thought I could launch an EXE file, perhaps by writing the parameters needed into environment variables (the Java class `System` can do that), but if the  exclusivities are generator-independant anyway there is truly no point in such efforts. (The Neo4j Spatial sample OSM one-street.osm was generated with CGImap, which is why I thought I have to use it too.)

**Comment by zerebubuth** [comment]
It looks like the Neo4J importer needs to be [specifically instructed](https://github.com/neo4j-contrib/spatial#importing-an-open-street-map-file) to open an OpenStreetMap format file. From the example given there, it looks like it'll work on an uncompressed XML format extract (the example is `sweden.osm`). If this is the case, then using CGImap is not necessary - the extracts and CGImap's XML output are the same. (Just make sure you have an XML file, generally ending `.osm.bz2`, not a binary file, generally ending `.osm.pbf`)

You can download all of OSM data from [planet.osm.org](http://planet.openstreetmap.org/). But the latest compressed XML file is 49GB, so starting with a smaller extract would be advisable. A list of various organisations providing different extracts is [on the OSM wiki](http://wiki.openstreetmap.org/wiki/Planet.osm#Country_and_area_extracts).

If you already have a database that you want to dump in XML format, then [Osmosis](http://wiki.openstreetmap.org/wiki/Osmosis) is a Java-based tool which can, amongst many other things, extract data from an "apidb" format database and dump it as OSM XML.

**Comment by ehx-v1** [comment]
Thanks, but I already asked the Neo4j Spatial team about the particular OSm requirements.
