### ISSUE TITLE
Clean shutdown

### ISSUE THREAD

**Issue by zerebubuth** [zerebubuth/openstreetmap-cgimap#109]
It can happen that CGImap gets a polite SIGTERM and tries to shut down its child processes, but they are stuck doing long queries (or something else) and don't terminate immediately.
- It would be nice if the behaviour were tunable. Perhaps a timeout after which to forcibly shut down long-running child processes?
- If possible, it would be nice for the parent to relinquish any listen sockets, so that at least a new CGImap process could be started, and start processing requests.
- CGImap currently will reload its output logfile when sent SIGHUP. It would be nice if it could reload all the child processes (without a complete shutdown) if sent a different signal.

**Comment by jronak** [comment]
- If the child process is handling a query we can set a busy flag(bool) and process the terminate request once it is not busy. We can make the parent wait till all of its child processes are done, probably use alarm and then forcibly terminate them?
- When the parent dies the listen sockets are anyway relinquished right ?
- So the child process shouldn't be killed and started, rather child process call reload by calling process request ?

**Comment by zerebubuth** [comment]
> If the child process is handling a query we can set a busy flag(bool) and process the terminate request once it is not busy.

Yes, you're exactly right. We have a mechanism for [flagging that the child process should terminate](https://github.com/zerebubuth/openstreetmap-cgimap/blob/5854e25df4b373712b66e5fbb903cea650d2313c/src/main.cpp#L171), which should shut down between handling requests. I'm not sure if the FCGI library buffers any connections, or whether there's more we should be doing when we [dispose of connections](https://github.com/zerebubuth/openstreetmap-cgimap/blob/5854e25df4b373712b66e5fbb903cea650d2313c/src/fcgi_request.cpp#L89).

> We can make the parent wait till all of its child processes are done, probably use alarm and then forcibly terminate them?

Yes, that sounds like a good plan.

I had said:

> If possible, it would be nice for the parent to relinquish any listen sockets

It looks like the parent [opens the socket](https://github.com/zerebubuth/openstreetmap-cgimap/blob/5854e25df4b373712b66e5fbb903cea650d2313c/src/main.cpp#L271-L285), but doesn't call `accept` on it itself. So it looks like I was wrong about that and the parent doesn't have to do anything to the listen socket, except `close` it, which I assume is already done as part of the FCGI shutdown. It looks like FCGI already sets `SO_REUSEADDR` on the socket, so another process could share that while this one is draining.

> So the child process shouldn't be killed and started, rather child process call reload by calling process request ?

I think the parent would start `instances` number of new children, keeping their PIDs in a `new_children` set of PIDs. Then it would send `SIGTERM` to all the existing (old) `children`, wait for them to all exit (or alarm and force them to shutdown), then swap `new_children` and `children`. I think the major (perhaps only?) effect of this would be to have all the children reconnect to the database. If that's the goal, perhaps it's simpler to use a different (`SIGUSR1`?) signal to do that without needing to swap out all the children?

I can't really remember _why_ I wanted this final point! The first two are to do with reloading or restarting the cgimap process during Chef runs or config changes, but I don't remember what the third one was about... @tomhughes does this ring any bells for you? Any idea what I might have been talking about?

**Comment by tomhughes** [comment]
So from the point of view of our production systems a custom restart signal doesn't help hugely as systemd has no way of using it - it always implements restart as a stop followed by a start. So it could only be used by sending it manually with `systemctl kill --kill=who=main --signal=X cgimap` or something.

It's true that restarts are an issue because it has to wait for long running requests, though with our current configuration what will actually happen is that if it hasn't exited after 90s everything will just get SIGKILL to force the exit.

If the main process simply passed on the SIGTERM and then exited without waiting then systemd could be configured to treat that as a successful stop after which it would start a new instance which should be able to listen for new connections if the listening socket is closed. Is the listening socket really closed though? Don't the children have it open still until they reach the end of the current request?

The ultimate would probably be socket activation so that cgimap didn't open the socket at all but was given it by systemd - then it could exit and be replaced by a new one and just carry on processing requests from the same socket...

**Comment by jronak** [comment]
If the parent dies without waiting for the children might be still processing a request and could be problematic if systemd expects all of its instances to be shut down too. Also yes children have that port till the current request is served. 
Yes, cgimap doesn't open any socket when socket/port param is not given and probably it can use the socket given to it by systemd, @zerebubuth this should be possible?

**Comment by zerebubuth** [comment]
Yes, I think it should be possible. Let me just check I've got the right idea:

1. Systemd starts Cgimap using socket activation and sends it a file descriptor for that socket.
2. That socket is already open, listening and bound, so Cgimap can fork and pass it to `fcgi_request::fcgi_request()` and from there to `FCGX_InitRequest()` and `FCGX_Accept_r()`.
3. When signalled, the parent process signals the forked children, setting their terminate flags. The parent then exits immediately.
4. A new Cgimap process is started by Systemd, and its children take over `accept`ing new connections.
5. The children of the previous process finish their outstanding requests, and the socket is still open to send the data back to their clients. They check the terminate flag before calling `accept` and then they exit.

That sounds like a good plan.

What happens if the old Cgimap children hang around for too long? Do we want them to set alarms when they get `SIGTERM` and `abort` if the alarm goes off before they're finished? Or can those old child processes hang around as long as they like?

**Comment by tomhughes** [comment]
That's basically it, yes. There's an introduction to socket activation at http://0pointer.de/blog/projects/socket-activation.html and http://0pointer.de/blog/projects/socket-activation2.html.

Basically you create a `cgimap.socket` unit along these lines:

```
[Unit]
Description=...

[Socket]
ListenStream=8000

[Install]
WantedBy=sockets.target
```

which would then activate `cgimap.service` whenever somebody connected to the socket (if it wasn't already running).

In the service you can either use `StandardInput=socket` to make it attach the socket to stdin when starting the service (only works if there is a single socket being listened on) or else you can use `sd_listen_fds` from libsystemd to find the socket(s) which basically just looks at `LISTEN_FDS` in the environment to get the count and then expects to find them at fd 3 and up.

If the service stops then systemd will revert to listening on the socket itself and restart the service if a new connection comes in. A restart is a stop+start so basically just short circuits the new start being triggered by a connection.

**Comment by tomhughes** [comment]
The full manual page for socket units is https://www.freedesktop.org/software/systemd/man/systemd.socket.html and for `sd_listen_fds` is https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html.

**Comment by zerebubuth** [comment]
Is there any way to (unit) test socket activation?

> If the service stops then systemd will revert to listening on the socket itself and restart the service if a new connection comes in.

Any idea how it does this? I went looking for an `unlisten` syscall, but couldn't find it. Does systemd actually "take back" the socket, or just trust that the service which stopped hasn't passed on the socket to something else which is still using it?

**Comment by tomhughes** [comment]
Well it keeps hold of the socket all the time, it just stops including it in the set of things it monitors with select/poll while the service is running. When the service stops it will start selecting on it again and start the service if the select triggers.

When it starts listening should depend on when it thinks the service is stopped, which is controlled by whether you tell it all the processes have to exit or only the main process (basically whether `KillMode` is `control-group` or `main`).

For unit testing I guess you would just have to have something create a listening socket and then start the process - not sure there are any special tools available.

**Comment by tomhughes** [comment]
Oh there is a `systemd-socket-activate` command (`systemd-activate` in older versions) but I'm not clear if/where Ubuntu package that...

**Comment by tomhughes** [comment]
Ah, it's in `/lib/systemd/systemd-activate` on Ubuntu.

**Comment by jronak** [comment]
@tomhughes Thanks for the man page and the article. Let me read about systemd-activate and come up with pr. Though I have a doubt, how would apache or lighttpd work with cgimap when socket is given by the systemd ?

**Comment by zerebubuth** [comment]
Looking at the [Lighttpd FastCGI docs](http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModFastCGI) it looks like if the configuration option `bin-path` is not set, then Lighttpd will connect to the configured UNIX `socket` or `host:port` combination. It seems that the `bin-path` option controls whether Lighttpd will try to start a FastCGI program itself, or just expect that one is already running.

Apache has similar options to configure FastCGI to expect a process already running on a given port, e.g: [the OSM website configuration](https://github.com/openstreetmap/chef/blob/75c5da85dcd5a6b5b66040dfd838c2bbf30ba4d5/cookbooks/web/templates/default/apache.backend.erb#L66-L73).

We would still want cgimap to be able to run in the ways it can at the moment; started by Lighttpd or creating it's own listen socket. It sounds useful to add socket activation as a 3rd method, though.

**Comment by jronak** [comment]
Thanks!, I shall try this and let you know

**Comment by mmd-osm** [comment]
I’m closing this one, as I believe the systemd integration is a bit too much complexity for cgimap.
