### ISSUE TITLE
Changeset 'comments_count' zero for changesets with notes

### ISSUE THREAD

**Issue by MichaelVL** [zerebubuth/openstreetmap-cgimap#116]
Changeset metadata contains the attribute 'comments_count' which I assume is 
the number of notes attached to a changeset. However, now I see that it is 
zero for changesets with comments, e.g. see the one below.  I suspect this is 
a recent change?  The API page does not mention this attribute AFAIK, so maybe 
this is an unused and deprecated feature?

http://www.openstreetmap.org/api/0.6/changeset/42754192?
include_discussion=true

**Comment by zerebubuth** [comment]
Hi!

Thanks for pointing this out. It looks like a bug, and that field should definitely be non-zero when there are comments present. I'll try and get it fixed ASAP.

**Comment by zerebubuth** [comment]
Fixed in ff414930a7db284f00dfb. Once it's built, I'll see about getting it deployed.

Thanks again for reporting this bug!

**Comment by zerebubuth** [comment]
Looks like this is live now (probably went live yesterday evening and I didn't notice). Please let me know if you notice any other bugs!
