### ISSUE TITLE
Should Cgimap use the MIME type?

### ISSUE THREAD

**Issue by zerebubuth** [zerebubuth/openstreetmap-cgimap#138]
OSM data should use the [`application/vnd.openstreetmap.data+xml`](https://www.iana.org/assignments/media-types/application/vnd.openstreetmap.data+xml) (plus charset?) MIME type.

However,

1. This isn't currently returned by the Rails code.
2. Many applications may be expecting the [`text/xml`](https://github.com/zerebubuth/openstreetmap-cgimap/blob/5854e25df4b373712b66e5fbb903cea650d2313c/src/mime_types.cpp#L13) MIME type, and might break if given another.

It should be safe to return `application/vnd.openstreetmap.data+xml` when it is present in the `Accept` header, though?

**Comment by mmd-osm** [comment]
Although @pnorman registered the MIME type 3 years ago (https://www.iana.org/assignments/media-types/application/vnd.openstreetmap.data+xml), I'm not sure this whole thing really took off.

Is this still something that would be relevant in 2019 or can be close this issue?

**Comment by pnorman** [comment]
We still should use the right mime type

**Comment by mmd-osm** [comment]
I’m closing this one for the time being. As long as this header isn’t implemented in the rails port and we need to keep both works in sync, there’s not much point keeping this one open.
