### ISSUE TITLE
Speed up /changesets call

### ISSUE THREAD

**Issue by bhousel** [zerebubuth/openstreetmap-cgimap#139]
Related to https://github.com/openstreetmap/iD/issues/4587

iD issues a [/changesets?user=](https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets) call to fetch a user's previous changeset comments.  We use this data when the user attempts to save, to show them a dropdown of previous changeset comments and let them reuse one or start typing and autocomplete.

This call is taking a while, regularly 5 seconds but often longer, between the request sent and TTFB (time to first byte) of the response.  The call itself only returns the user's 100 most recent changesets, so it seems like it should be able to complete fairly quickly.

I went looking through the cgimap code for this and couldn't find it - is this a call still handled by the Rails site?

**Comment by pnorman** [comment]
I think this is part of the rails port, and doubt it would gain much from moving it to cgimap. The rails-generated SQL is probably fine, and there aren't a huge number of objects to handle when it's limited to 100.

If I had to guess, this might be an operations problem resulting from lack of maintenance on the relevant table, which has a high rate of churn, but I don't have any evidence for this.

**Comment by tomhughes** [comment]
Well that's not an API call so it's not really a candidate for cgimap and iD should probably have asked for a proper api call rather than using that.

**Comment by tomhughes** [comment]
Oh hang on the URL that @bhousel gave doesn't match what he linked to - what he linked to is an API call but not one that cgimap currently implements.

**Comment by Zverik** [comment]
I also use this endpoint to get a few latest changesets for "OSM Streak" project, and it takes a while, even for a couple changesets (I filter by user and date). You can see it for youself on http://streak.osmz.ru/ — the list (or "you haven't edited" message) appears a few seconds after the page loads, not instantly.

**Comment by tomhughes** [comment]
I've pushed https://github.com/openstreetmap/openstreetmap-website/commit/2c52c91b393f087df60c3f6765905cbc8248e3e7 which should speed up the rails code while we're waiting to get this in cgimap.

**Comment by Zverik** [comment]
Thanks Tom!

**Comment by bhousel** [comment]
Thanks Tom - whatever you did seems to have dropped the times from 5sec down to half a second..

I'll leave it up to the maintainers whether they want to leave this issue open as a possible cgimap enhancement or close it.

**Comment by mmd-osm** [comment]
I think it's okay to keep this one. It will probably the last API call needed (after changeset create,update/close) to run a whole editing session on cgimap only. Also, it shouldn't be too difficult to implement.

I someone feels like doing some work on this, take a look at https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/api/changesets_controller.rb#L202-L223 and try to turn that into some single SQL statement:

```
  select * from changesets 
   where (id = ANY($1) or $2 = true)
     and (user_id = ANY($3) or $4 = true)
     and (created_at = $5 or $6 = true);
```

$2, $4, $6 and meant to enable/disable the previous condition.

**Comment by mmd-osm** [comment]
Ok, 2.5 years later, no one picked this up. So let’s just close it.
