### ISSUE TITLE
Integrate Codecov for test coverage

### ISSUE THREAD

**Issue by Komzpa** [zerebubuth/openstreetmap-cgimap#141]
We've enabled codecov for PostGIS travis builds and that immediately pointed out dead code to remove. It is also useful to get a quick glance of pull request completeness.

Example of enabling:
https://github.com/codecov/example-c

This also needs permission from repository admins.

**Comment by mmd-osm** [comment]
See https://codecov.io/gh/mmd-osm/openstreetmap-cgimap/branch/codecov for an example.

**Comment by mmd-osm** [comment]
Closing here, as I don't have permission to set this up on this repo, and codecov works on my fork.

Relevant config can be found under: https://github.com/mmd-osm/openstreetmap-cgimap/blob/codecov/.travis.yml
