### ISSUE TITLE
Changeset - incorrect open status with timezone != utc-0

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#150]
Situation: CGImap runs on a server in UTC+2 timezone. The changeset call /api/0.6/changeset/xxx returns a changeset where the status is "closed", although the changeset will only close 1 hour in the future. For further discussion see details at https://github.com/westnordost/StreetComplete/issues/562#issuecomment-404394683

`now` is initialized with local time (which is UTC+2):

https://github.com/zerebubuth/openstreetmap-cgimap/blob/83185f590317d7f1c5cf9c5ba65b48e6970b5456/src/main.cpp#L183

Comparison doesn't take UTC+2 / UTC+0 difference into account: 

https://github.com/zerebubuth/openstreetmap-cgimap/blob/fdc2523c4293345c0b831740890aa8cd91c0b215/src/output_formatter.cpp#L59-L62

Processing should be based on UTC+0, regardless of the local timezone.

**Comment by tomhughes** [comment]
Note that all OSM servers run in UTC all the time anyway.

**Comment by mmd-osm** [comment]
Right, I wanted to keep this in line with what we did here: https://github.com/openstreetmap/openstreetmap-website/issues/1688, i.e. no hard requirement to run on UTC+0 timezone.

**Comment by tomhughes** [comment]
So just change `local_time` to `universal_time` then ;-)
