### ISSUE TITLE
[Meta] Update other cgimap repos

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#160]
It seems like there are at least two other cgimap repos, which lag behind this repo in the meantime. I have no idea what they're used for or how to keep them up in sync.

* https://git.openstreetmap.org/?p=cgimap.git
* https://github.com/openstreetmap/cgimap

**Comment by tomhughes** [comment]
The first one was used for deployment purposes when we were building from source and is largely redundant now.

The second one probably mirrors the first.

**Comment by mmd-osm** [comment]
Yes, that makes sense. Do you think it's worthwhile trying to keep them in sync in the future, although we're using a different build process now, or could they be marked as deprecated and have them point to the zerebubuth repo instead?

People might just look at the openstreetmap/cgimap repo, think that's the current one and miss out on newer features or send in pull requests for outdated software.

**Comment by simonpoole** [comment]
@mmd-osm @tomhughes shouldn't this repo be in the openstreetmap org in any case due to some more fundamental reasons (assuming that @zerebubuth aggress).

**Comment by tomhughes** [comment]
Well he didn't agree which is why it wasn't moved.

**Comment by mmd-osm** [comment]
Can't really help with this one, that's something only repo owners can do.

**Comment by zerebubuth** [comment]
I can't think of any reason to move this to the centrally-controlled openstreetmap organisation, so I'd be interested to hear in more detail what reasons I've overlooked.

However, to the original point: While I disagree, I also haven't been involved for a while, so I will defer to the consensus viewpoint. If you all think it is important that it be moved, then I will move it.

**Comment by simonpoole** [comment]
@zerebubuth it is simply a question of discoverability, so either the repo is in the least centrally-controlled centrally controlled organisation of all times, or there is a current mirror there (OK and there is the bus-factor too).

**Comment by zerebubuth** [comment]
My experience is that many - perhaps most - people look tend to treat Github URLs as `github.com/$OWNER/$PROJECT`, and therefore unfortunately conflate a project being in an organisation with that organisation being its author or maintainer. In my opinion, this diminishes the actual contributors to a project.

Thankfully with Git, the bus factor seems like it would be less important. Even if I decided to follow `_why`'s example and erase all my repos, there are still likely many checked-out copies and mirrors and the code wouldn't be lost. The issues and PRs would, but that wouldn't prevent the code from continuing to be developed under a different repo. (And is perhaps an argument for moving away from Github towards something that would allow issues and PR discussions to be backed up.)

Philosophical differences aside, my offer to move it stands, as long as the people (or person) who're doing all the actual work want me to.

**Comment by mmd-osm** [comment]
I'd be happy to keep everything as is, at least as long as we're still chasing bugs.

**Comment by simonpoole** [comment]
> 
> 
> My experience is that many - perhaps most - people look tend to treat Github URLs as `github.com/$OWNER/$PROJECT`, and therefore unfortunately conflate a project being in an organisation with that organisation being its author or maintainer. In my opinion, this diminishes the actual contributors to a project.

My experience is that many - perhaps most-  projects with the Github URLs as `github.com/$OWNER/$PROJECT` are dead and unmaintained, if you want to use the project as a reference in your CV, then you should perhaps consider showing signs of life now and then, 

From an OSM pov, it is key part of the current software stack and we don't f**king care who originally conceived it (aka dog eats dog), but just about making it easy to raise issues against its behaviour and in general keeping it current.

**Comment by mmd-osm** [comment]
As far as our experience with osmosis is concerned, being part of the openstreetmap GitHub organization doesn't guarantee that the piece of software is still maintained, and pull requests merged (https://github.com/openstreetmap/osmosis/).

Pretty much the same applies to mod_tile, which has some serious shortcomings in the area of queue handling, a fair amount of issues and pull requests, it is part of the core OSM infrastructure, yet unmaintained since years.

I think there are some more fundamental issues here which need to be addressed first.

**Comment by zerebubuth** [comment]
> if you want to use the project as a reference in your CV

I'm sorry if I gave the impression that this was about my vanity. What I meant was that people who'd contributed over the course of many years, even if not currently active, should be accorded due respect for those contributions.

> you should perhaps consider showing signs of life now and then

Do you think we might have better luck convincing lapsed contributors to return, or new contributors to join, by being civil towards them?

> we don't f**king care who originally conceived it (aka dog eats dog), but just about making it easy to raise issues against its behaviour and in general keeping it current.

In the specific case of cgimap, I'm pretty sure I didn't originally conceive it. I merely spent seven years putting in the effort and attempting to improve its behaviour and, as you say, "keep it current". I'm fully in favour of making it easy to report issues, but the flip side of that is that someone needs to be working to fix those issues. To me, both seem orthogonal to which URL the repo uses.

I think we've gone a little off-topic from the original issue description.

**Comment by mmd-osm** [comment]
_[marking most of the previous discussion as off-topic]_
So back to the original question: how do keep the other mirrors of this repo in sync?
