### ISSUE TITLE
Missing oauth header file after make install

### ISSUE THREAD

**Issue by gravitystorm** [zerebubuth/openstreetmap-cgimap#162]
I'm trying to compile cgimap-ruby (https://github.com/zerebubuth/cgimap-ruby/pull/6) but run into a problem that I think lies in cgimap itself. My script compiles and installs cgimap 0.6.2, and then the patched cgimap-ruby builds against the installed version.

The mkmf log for cgimap-ruby says:

```
have_library: checking for make_apidb_backend() in -lcgimap_apidb... -------------------- no
```

but this is misleading, since the actual complaint is:

```
In file included from /usr/local/include/cgimap/backend/apidb/apidb.hpp:5:0,
                 from conftest.c:3:
/usr/local/include/cgimap/backend.hpp:9:28: fatal error: cgimap/oauth.hpp: No such file or directory
compilation terminated.
```
Indeed that file is not in the /usr/local/include/cgimap/ directory after installation:

```
kitchen@13cffd2d376a:~$  ls /usr/local/include/cgimap/
api06        data_selection.hpp  output_buffer.hpp     request_helpers.hpp
backend      handler.hpp         output_formatter.hpp  routes.hpp
backend.hpp  http.hpp            process_request.hpp   types.hpp
bbox.hpp     logger.hpp          rate_limiter.hpp      zlib.hpp
config.hpp   mime_types.hpp      request.hpp
```
I *think* that's because it's not listed in the [Makefile.am](https://github.com/zerebubuth/openstreetmap-cgimap/blob/eee71075ad27de24ffcdc8b48023e4fe01f86154/Makefile.am#L9-L26) but this is at the limit of my understanding.

**Comment by mmd-osm** [comment]
You're absolutely right. I already fixed this as part of https://github.com/zerebubuth/openstreetmap-cgimap/blob/41be92f3d0b265888d35cb36b71e2c003e4adca3/Makefile.am in the feature/bulk_upload branch, but that's not yet merged into master yet.

**Comment by gravitystorm** [comment]
Thanks @mmd-osm . In the meantime I just hacked the Makefile.am for the one oauth header, recompiled and got the next steps working. So no rush from me at the moment.
