### ISSUE TITLE
Redistributable binary needed

### ISSUE THREAD

**Issue by baerbock** [zerebubuth/openstreetmap-cgimap#169]
Hi mmd,

that the ./openstreetmap-cgimap executable is only a wrapper makes me a big headache.

```
# The ../openstreetmap-cgimap program cannot be directly executed until all the libtool
# libraries that it depends on are installed.
#
# This wrapper script should never be moved out of the build directory.
# If it is, it will not operate correctly.
```

How can I create a "real" binary for proper deb/rpm/tar.xz packaging?

**Comment by tomhughes** [comment]
That's just libtool - if you run `make install` then it should install correctly.

I don't know how Debian normally handles this - in Fedora we run `make install` as part of the build process and then package the installed files rather than trying to package from the build tree.

**Comment by tomhughes** [comment]
The "real" program is `.libs/openstreetmap-cgimap` by the way but I wouldn't recommend just packaging that because I'm not sure what, if anything, libtool might do to it as part of the install process.

**Comment by mmd-osm** [comment]
We also have about five libcgimap-* shared library objects, which are part of the installation. Maybe you could take a look at the build instructions we use for Ubuntu Bionic: https://github.com/zerebubuth/openstreetmap-cgimap/tree/ubuntu/bionic/debian

**Comment by baerbock** [comment]
Thank you all very much. `make install` indeed works, but ignores my DESTDIR and always wants to go to /usr/local

**Comment by tomhughes** [comment]
That seems strange - it's all automake and that normally respects DESTDIR.

**Comment by tomhughes** [comment]
It seems to work for me (it installs to `$DESTDIR/usr/local`, but that it normal unless you configure with `--prefix=/usr`).

**Comment by baerbock** [comment]
Ok, probably I was a little dumb ...
