### ISSUE TITLE
Syntax for cgimap.conf

### ISSUE THREAD

**Issue by baerbock** [zerebubuth/openstreetmap-cgimap#170]
Hi Tom & mmd,

thanks to your help I've succeeded in compiling cgimap and now trying to deploy it.

I'm using Apache (called [httpd](https://www.archlinux.org/packages/extra/x86_64/apache/) in ArchLinux) with mod_fcgid.

But I'm out of practice when it comes to Apache. It even complains "Invalid command 'RewriteEngine'" when using the example conf:

```
<Directory /etc/httpd/api>

    RewriteEngine on

    RewriteRule ^0\.6/map$ - [L,H=fcgi:127.0.0.1:8000]
    RewriteRule ^0\.6/(nodes|ways|relations)$ - [L,H=fcgi:127.0.0.1:8000]
    RewriteRule ^0\.6/(way|relation)/([^/]+)/full$ - [L,H=fcgi:127.0.0.1:8000]

    RewriteCond %{REQUEST_METHOD} ^(GET|HEAD)$
    RewriteRule ^0\.6/(node|way|relation)/([^/]+)$ - [L,H=fcgi:127.0.0.1:8000]

    RewriteRule ^(.*) http://api.openstreetmap.org/api/$1 [P]
</Directory>

ProxyPreserveHost On
```

Do you personally use a more modern version of cgimap.conf?

**Comment by tomhughes** [comment]
Well that just means you haven't got `mod_rewrite` enabled.

**Comment by baerbock** [comment]
Yes, it works! But despite I have had imported Andorra from osm.pbf the API doesn't find any data (at the place where Andorra is). Here is a screenshot of QGIS connected to my local postgis osm database:

![screenshot](https://user-images.githubusercontent.com/45873962/51856771-d3c7cd80-2330-11e9-9d43-9b52aeb7e218.jpg)

**Comment by mmd-osm** [comment]
It seems you're using osm2pgsql to load your database? That won't work with cgimap, you need to use osmosis with an apidb schema.

If you don't mind, please do a follow up on this topic on https://help.openstreetmap.org/ which is better sutied for these kind of howto quetions.

**Comment by mmd-osm** [comment]
One more comment: apidb doesn’t use any Postgis extension at all, it’s just a plain postgresql db.
Btw: what are you trying to achieve with your setup?

**Comment by mmd-osm** [comment]
As @woodpeck answered your question, I'm closing here.
