### ISSUE TITLE
history api call for node returns versions  in wrong order

### ISSUE THREAD

**Issue by GerdP** [zerebubuth/openstreetmap-cgimap#182]
The call
https://www.openstreetmap.org/api/0.6/node/324302111/history
returns the three versions for the node in the wrong (at least unusual) order v1, v3, v2.
Attached is the result
[node-324302111-history.result.txt](https://github.com/zerebubuth/openstreetmap-cgimap/files/3220074/node-324302111-history.result.txt)

**Comment by tomhughes** [comment]
Also specific to running in readonly mode.
