### ISSUE TITLE
Bad Request (400) - Version may not be negative

### ISSUE THREAD

**Issue by westnordost** [zerebubuth/openstreetmap-cgimap#188]
Repost/moved from https://github.com/openstreetmap/operations/issues/303

### Reproduction
Try uploading an element with the `version` attribute set to `-1`: Into an open changeset upload via `POST changeset/$id/upload` with the body being something like 
```<osmChange><modify><node id='1' version='-1' lat='1' lon='1'/></modify></osmChange>```.

cgimap will return `Bad Request (400) - Version may not be negative`

The rails implementation probably\*  used to return a `Conflict (409)` in this case.

This change in behavior caused a bug in StreetComplete to surface: https://github.com/westnordost/StreetComplete/issues/1408

\* did not check, but it seems so, don't know where I can find the source

**Comment by simonpoole** [comment]
While one can argue for bug by bug compatibility with the rails-port, I believe this one should actually be fixed there and not here, as it lets apps doing broken things slip through. @gravitystorm ?

**Comment by mmd-osm** [comment]
Following the argument on https://github.com/openstreetmap/operations/issues/303#issuecomment-497067942, I'm closing here, as I think everyone agrees we shouldn't accept negative version numbers.
