### ISSUE TITLE
412 Precondition Failed when trying to upload old version of a way

### ISSUE THREAD

**Issue by westnordost** [zerebubuth/openstreetmap-cgimap#194]
Uploading an old version of a way should always yield a **409 Conflict** error.

However, in the case that nodes of the way in question were deleted in the new version of the way, instead, a **412 Precondition Failed** is returned.
This is because the check for the nodes used in the way in `ApiDB_Way_Updater::process_modify_ways` is [done before](https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/backend/apidb/changeset_upload/way_updater.cpp#L163) the [check for the versions](https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/backend/apidb/changeset_upload/way_updater.cpp#L180). 

I am getting error reports about this only recently for StreetComplete, so I assume that the behavior used to be different for the ruby-based implementation which got replaced by cgimap a few days ago.

**Comment by mmd-osm** [comment]
Thank you for the detailed report! It looks like your analysis is spot on and the error code should be 409 rather than 412 in that case. I probably need to address the same issue for relations as well and update unit tests for both cases.

**Comment by mmd-osm** [comment]
The fix should appear shortly on https://master.apis.dev.openstreetmap.org as cgimap 0.7.5. If you like you can do some more testing there while I prepare the new release.

**Comment by mmd-osm** [comment]
I tested this on master, running on 0.7.5 now:

1. Start JOSM
2. Start iD
3. Load Way 4304391865 in both editors
4. In iD: remove one node, upload
5. In JOSM: add new k=v pair, upload
6. JOSM upload now complains about the version conflict
-> do conflict resolution in JOSM

Changesets: 148996 (iD), and 148997 (JOSM).

@tomhughes : new release 0.7.5 is available on launchpad now
