### ISSUE TITLE
Diff upload 412 error message difference

### ISSUE THREAD

**Issue by simonpoole** [zerebubuth/openstreetmap-cgimap#210]
The messages returned on a 412 error don't start with `Precondition failed: `

Example from a rails-port without cgi-map:

`Precondition failed: Node 23 is still used by ways 9.`

Example from the dev sandbox:

`Node 4318231207 is still used by ways 4305438501.`

**Comment by mmd-osm** [comment]
Do you see the same issue on prod?

**Comment by mmd-osm** [comment]
One issue I see is that the Rails port doesn't adhere to the API 0.6 documentation on https://wiki.openstreetmap.org/wiki/API_v0.6. I cannot find any reference where it says that the error message should be prefixed by "Precondition Failed:".

Precondition Failed is implicitly clear by the HTTP 412 error code, i.e. there's no real need to add that text to the error message again.

@tomhughes: what would be your assessment here? Which one is right? The Rails port, the OSM API 0.6 docs, neither one? 

JOSM doesn't have that issue, because they don't include "Precondition Failed:" in their regex parsing string.

**Comment by tomhughes** [comment]
The code. Always the code. The "documentation" in the wiki is written by heaven knows who based on who knows what. It's certainly not maintained by any of the developers, nor is it a specification or in any way official.

**Comment by simonpoole** [comment]
I think you are being a tad bit optimistic about the documentation, most of it was written based on the behaviour of osm.org, not as a spec (if it was, cgi-map would still be wrong as it always pluralizes ways and relations in the message(, Pinging @gravitystorm

**Comment by mmd-osm** [comment]
@simonpoole : well, the documentation says: _"Note when returned as a result of a OsmChange upload operation the error messages contain a spurious plural "s" as in "... still used by ways ...", "... still used by relations ..." even when only 1 way or relation id is returned, as this implies multiple ids can be returned if the deleted object was/is a member of multiple üarent objects, these ids are seperated by commas."

This section was added by a wiki user identifying themselves as "SimonPoole" on 19. Aug. 2016‎. :)

**Comment by simonpoole** [comment]
I think that proves my point that it is simply documentation of current behaviour, not a spec.

**Comment by mmd-osm** [comment]
Ok, based on https://github.com/MarcusWolschon/osmeditor4android/commit/2f8c701795eb117bc75e6bc6029d21a7750638bc, I'd say, we should be good to include this fix in 0.8.0, and skip the 0.7.6 release. Once the pull request gets merged into master, testing on dev will be possible. 0.8.0 release to production is still TBD.

**Comment by simonpoole** [comment]
Due to the way this fails irl (and that it isn't straightforward to actually create such a conflict without cheating) are you sure that id and JOSM don't have the error?

**Comment by mmd-osm** [comment]
Here’s the respective parser code for Josm: https://github.com/openstreetmap/josm/blob/21826a3abc29e710580a42dd0078febd0ec16d48/src/org/openstreetmap/josm/tools/ExceptionUtil.java#L105

iD sends an additional attribute to suppress the error altogether (deleting a still referenced object that is)

**Comment by mmd-osm** [comment]
Related code on Rails port: https://github.com/openstreetmap/openstreetmap-website/search?q=%22Precondition+failed%3A%22&unscoped_q=%22Precondition+failed%3A%22
