### ISSUE TITLE
How to i understand about scripts/cgimap.init ?

### ISSUE THREAD

**Issue by cuongnc5** [zerebubuth/openstreetmap-cgimap#212]
I can not understand about variable in cgimap
Ex:
CGIMAP_RATELIMIT=102400; export CGIMAP_RATELIMIT
CGIMAP_MAXDEBT=250; export CGIMAP_MAXDEBT

Can i edit value  of CGIMAP_RATELIMIT, CGIMAP_MAXDEBT ?
ex: my PC properties: RAM 31GB, CPU 16 core. I need change CGIMAP_RATELIMIT to large value ?

**Comment by tomhughes** [comment]
That depends on how you are starting the cgimap server - you need to set them as environment variables in the environment when starting it.

**Comment by cuongnc5** [comment]
I understand It is environment variables. But i don't understand about  value 102400, 250. Can I change  it?

**Comment by tomhughes** [comment]
Of course, just take your text editor and edit the script to increase the values.

**Comment by cuongnc5** [comment]
whose value CGIMAP_RATELIMIT=102400 mean Rate limit is 102400 request per month or day?
What is  CGIMAP_MAXDEBT mean?

**Comment by tomhughes** [comment]
The rate limit is the important one - it's the number of bytes you can download every second (on average) so if you want to be able to download more data then increase that.

The maxdebt value is total number of bytes you can burst to before the limiting kicks in but it only matters to allow you to temporarily exceed the rate limit so if you have increased the rate limit enough it won't have any effect.

**Comment by cuongnc5** [comment]
Oh. I understood. Thank you so much.
