### ISSUE TITLE
Implement trackpoints API call in cgimap

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#230]
Not sure if we really need this at all in cgimap. If someone has some comments on this topic, please post them here.

I created this as follow up for https://trac.openstreetmap.org/ticket/3125

**Comment by pnorman** [comment]
It doesn't seem like an important call to port to me, absent some data about how often it is called and someone looking at optimizing the rails call first.

**Comment by mmd-osm** [comment]
Trackpoints endpoint shows pretty poor performance recently, which may be due to a large number of index scans on table _gpx_files_. So yes, this needs some further investigation on Rails side first.

![trkpts1](https://user-images.githubusercontent.com/5842757/106392988-b1bc2680-63f4-11eb-94a8-bdb4de8bd0d9.png)
![trkpts2](https://user-images.githubusercontent.com/5842757/106392991-b385ea00-63f4-11eb-8a00-1bcea2054bcb.png)

**Comment by tomhughes** [comment]
Are you saying there has been a deterioration in performance? Relative to what baseline?

Index scans are good - obviously less of them is better but that generally means getting less data! They're better than doing table scans though...

**Comment by mmd-osm** [comment]
Prometheus stats seem to be limited to the last 15 days, so I don't have longer term data available. It seemed a bit unusual that response times are in the 1-2 minute range over the past two days. This may be just a coincidence caused by some heavy users of that endpoint. I don't know what kind of data they're requesting right now.

![trkpts3](https://user-images.githubusercontent.com/5842757/106393622-74f22e80-63f8-11eb-8776-772bbe0026fd.png)
