### ISSUE TITLE
OSM Dev Port 3000

### ISSUE THREAD

**Issue by Legolash2o** [zerebubuth/openstreetmap-cgimap#231]
I'm currently running my OSM server in dev mode on 3000. 

Is there any additional steps or config changes to get this to work with that please?

Update: 
If using [this](https://wiki.openstreetmap.org/wiki/Cgimap/install) guide. I'm on the very last step for configuring apache

If using [this](https://github.com/zerebubuth/openstreetmap-cgimap) guide. I'm upto the 'Setup' part. I've created a user account and given execute permissions. It's just the apache stuff I'm stuck on.

**Comment by mmd-osm** [comment]
I would recommend to the a look at the following resources: 

https://github.com/mmd-osm/openstreetmap-cgimap/blob/patch/docker/Dockerfile
https://github.com/mmd-osm/openstreetmap-cgimap/blob/patch/docker/lighttpd.conf

**Comment by Legolash2o** [comment]
Update: 
If using [this](https://wiki.openstreetmap.org/wiki/Cgimap/install) guide. I'm on the very last step for configuring apache

If using [this](https://github.com/zerebubuth/openstreetmap-cgimap) guide. I'm upto the 'Setup' part. I've created a user account and given execute permissions. It's just the apache stuff I'm stuck on.

**Comment by Legolash2o** [comment]
Thanks for the links.

So on the Dockerile link: I follow the steps and change 8000 to 3000?.

To be honest, the apache link just confused me. Change the virtual host to 3000 instead of 80?

Thanks again.

**Comment by mmd-osm** [comment]
Port 3000 is the port used by the Rails port (HTTP protocol)
Port 8000 is used by CGImap (FastCGI protocol(!))

Apache (on another port, e.g. 1080) sends some of the requests to the Rails port via HTTP protocol, or to CGImap (via FastCGI protocol).

**Comment by tomhughes** [comment]
Well if rails is running on 3000 then that's probably using the builtin server rather than apache, though you could use apache in front as a proxy I guess.

**Comment by mmd-osm** [comment]
So it seems there are no further questions here...
