### ISSUE TITLE
Adding OAuth2 support

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#238]
See https://github.com/openstreetmap/openstreetmap-website/issues/1408

**Comment by mmd-osm** [comment]
@cquest, @frodrigo: I've seen the comments in https://annuel.framapad.org/p/N_IDAQXYLHswlpU2s3oE

The cgimap part is not relevant for your Discourse OAuth2 integration, all you need is in the OSM website issue.

**Comment by frodrigo** [comment]
We was asking ourself about the status of the OAuth2 on the last OSM-FR chapter meeting. If the implementation is still going on or has been stoped.
But after looking at https://github.com/openstreetmap/openstreetmap-website/compare/master...tomhughes:doorkeeper I see @tomhughes is still working on it. Don't worry, it's not for pressure, but rather to provide in a way or in an other resources if necessary.

**Comment by mmd-osm** [comment]
Feature branch https://github.com/zerebubuth/openstreetmap-cgimap/tree/feature/oauth2 now comes with oauth2 support.

**Comment by mmd-osm** [comment]
@tomhughes : I wanted to double check what your plans are to include CGImap in the current oauth2 dev instance test cycle. Moving this code right to production without any testing doesn't seem like a good approach to me.

**Comment by tomhughes** [comment]
I've added it to the test instance now.

**Comment by mmd-osm** [comment]
@cquest, @frodrigo: as a FYI: OAuth2 is in production now, you might want to check, how https://github.com/openstreetmap/openstreetmap-website/issues/1408#issuecomment-707346587 could be useful for your osm-fr discourse instance.
