### ISSUE TITLE
How to deploy on CentOS

### ISSUE THREAD

**Issue by ubill88** [zerebubuth/openstreetmap-cgimap#243]
Hi, I'm a new user that using a CentOS server.
I'm facing a problem to start CGImap on apache2.
There is no apache2 but only httpd on CentOS, and there is no a2ensite either.
I've been able to run
`./openstreetmap-cgimap --socket :54321 --backend apidb \ --dbname openstreetmap`
But I don't have any clue about the apache2 part.
Also, **cgimap/scripts/cgimap.conf seems** not working on **/etc/httpd/sites-available/**
Is there an example about deploying on CentOS?
Please give me a hint! Thanks in advance!

Best regards.

**Comment by tomhughes** [comment]
The a2ensite script is not standard apache - it's an artefact of debian/ubuntu packaging.

This is not a cgimap question though, it's an apache configuration question, so you should really be reading the apache documentation and editing the appropriate files in `/etc/httpd` in line with that documentation.

**Comment by mmd-osm** [comment]
Right, as we're not officially supporting CentOS, you're a bit on your own here. You need to read the relevant docs to find out how to run FastCGI binaries on CentOS, or find some CentOS group who can help you there.

**Comment by ubill88** [comment]
Thanks for the reply @tomhughes @mmd-osm .
Does the docker part here:
https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/Dockerfile
includes the apache2 part? I can't find any related part here.
I am wondering if I can use a ubuntu based docker container to run on my CentOS server.

**Comment by mmd-osm** [comment]
No, the Dockerfile doesn’t include any webserver. See https://github.com/zerebubuth/openstreetmap-cgimap/pull/213 as an example on how to use lighttpd.
