### ISSUE TITLE
Stuck on installation

### ISSUE THREAD

**Issue by Legolash2o** [zerebubuth/openstreetmap-cgimap#244]
Hello, I've followed the steps on the guide up to "Specifying configuration options" but I'm struggling to proceed further. 

I can get the webpage to run on port 31337 but it returns service unavailable on the debug console. I've tried attempting config changes including specifying a ini file but I receive the following message. My main OSM site is currently running on port 3000.

Error: FCGI port or UNIX socket not set properly, please use the --socket option (caused by ENOTSOCK).

I've also tried './openstreetmap-cgimap --socket :54321 --backend apidb --configfile ./testconfig.ini' but I'm still receiving service not available.

I'm also using lighttpd and Ubuntu 20.04.

Any help would be appreciated. Thank you.

**Comment by mmd-osm** [comment]
Can you post the section fastcgi.server of your lighttpd.conf config file? Probably this is pointing to a wrong port.

Also take a look at the „For use with Dockerfile“ section in the provided lighttpd.conf config file. If you run your cgimap binary on port 54321, you need to change port 8000 to 54321.

**Comment by Legolash2o** [comment]
Yeah, sure. Thanks for the reply. I changed the extension from conf to txt.

[lighttpd.txt](https://github.com/zerebubuth/openstreetmap-cgimap/files/6252624/lighttpd.txt)

**Comment by mmd-osm** [comment]
Make sure that no other lighttpd deamon is running, then start your lighttpd from command line as follows:

```
lighttpd -D -f lighttpd.conf
```

Do you see any error messages, if so, which ones?

**Comment by Legolash2o** [comment]
When I run the command you suggested I get the following in the console (before running any API)

Error: FATAL:  password authentication failed for user "api"
FATAL:  password authentication failed for user "api"

Thanks again.

**Comment by mmd-osm** [comment]
Ok, I'm closing here, as it's an obvious config issue.

**Comment by Legolash2o** [comment]
Is the username and password required same as the database password?

**Comment by mmd-osm** [comment]
Yes, those are needed to log on to the same database which you hopefully created beforehand using the Rails port.

**Comment by Legolash2o** [comment]
Thanks, I'll try those credentials and try again in the morning. I've already had a database setup and working for a while.

**Comment by Legolash2o** [comment]
Managed to the solve the problem. It may be worth expanding on the configuration section of the read me to mentioned that -D can be used to debug any config issues.

Thanks again for the help!
