### ISSUE TITLE
Can't clone the repo.

### ISSUE THREAD

**Issue by pouriamoosavi** [zerebubuth/openstreetmap-cgimap#253]
Hi hope you are well

The cloning command `git clone git://github.com/zerebubuth/openstreetmap-cgimap.git` stuck for some reason and do nothing. I tested it both on an AWS E2C and my own PC. It shows no error and nothing will appear on the output. I'm not sure what is the problem. Downloading zip file with wget or similar tools however works fine.  `wget https://github.com/zerebubuth/openstreetmap-cgimap/archive/refs/heads/master.zip`

By the way I have this issue with this repo only. I've tested with some other github repos and they work fine.

**Comment by tomhughes** [comment]
I'm pretty sure it's just that git protocol checkouts are not supported and have been blocked - use https instead.
