### ISSUE TITLE
Clarify and document restrictions on key and value strings.

### ISSUE THREAD

**Issue by xorgy** [zerebubuth/openstreetmap-cgimap#278]
As discussed in https://github.com/openstreetmap/openstreetmap-website/issues/3706 and https://github.com/openstreetmap/openstreetmap-website/issues/2025, the restrictions on keys and values are not well documented.

In practice, it seems that openstreetmap-cgimap will accept any string that is 255 or fewer valid Unicode codepoints. Tests in openstreetmap-cgimap check this behaviour.

**Comment by mmd-osm** [comment]
Relevant unit test can be found here: https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/test/test_parse_osmchange_input.cpp#L444
