### ISSUE TITLE
cgimap should check the user state

### ISSUE THREAD

**Issue by tomhughes** [zerebubuth/openstreetmap-cgimap#283]
We should make cgimap check that the user state is `active` or `confirmed` and ignore any authentication for invalid users, either rejecting the request or processing it as if the user was unauthenticated for read requests.

**Comment by mmd-osm** [comment]
By the way, we also need to fix this on Rails, because changeset creation still happens there.

**Comment by tomhughes** [comment]
Already done in https://github.com/openstreetmap/openstreetmap-website/commit/9cb7a7b36b8ee68502d5da94db6bc3dda29051b4.
