### ISSUE TITLE
Increase (or remove) the rate limit for administrators/moderators

### ISSUE THREAD

**Issue by Zaczero** [zerebubuth/openstreetmap-cgimap#290]
Currently, [Thanos](https://github.com/Zaczero/Thanos) *(tool used by DWG)* encounters difficulties with mass-reverts due to rapidly reaching [the rate limit](https://github.com/openstreetmap/cgimap/blob/704c171bccf9f6a41811dc076cd9c405e45ab463/src/process_request.cpp#L511). This results in considerable delays for extensive revert tasks, sometimes requiring several hours of waiting. Ideally, the rate limit behavior should be adjusted for OSM moderation purposes.

**Comment by tomhughes** [comment]
To be clear while this repository is the place to ask for the ability to set a higher rate limit for moderators the actual decision of what rate limits to set is a an operational matter that is out of scope here.

**Comment by mmd-osm** [comment]
@tomhughes : In case you need an immediate workaround, you could delete the respective keys directly on memcached. Syntax is as follows, where 1, 2, 3 corresponds to the user id. This could be part of some scheduled script.

```
delete cgimap:user:1
delete cgimap:user:2
delete cgimap:user:3
quit
```

**Comment by DavidKarlas** [comment]
I opened PR in attempt to fix this issue: https://github.com/zerebubuth/openstreetmap-cgimap/pull/294
Let me know if you would prefer increasing limit instead of increasing it, I can make change to increase limit instead...

**Comment by mmd-osm** [comment]
@Zaczero : I was wondering a bit why we're even hitting the rate limit here.

The way rate limiting works today is that we're counting the size of an API response towards the user quota. In case of /map or some full history calls, users should be throttled fairly quickly.

However, in case of changeset uploads, we're sending back a tiny diffResult XML document with about 100 bytes per created/changed/deleted object. A user would have to upload more than a million objects before they're hitting rate limiting.

Presumably, changeset upload is not the only you're calling. It would be good to get some idea, what kind of data volume to expect for moderators. Maybe we have to revisit our 32bit field here.

**Comment by Zaczero** [comment]
We're dealing with hundreds of changeset XMLs, each with a size of 5000-10000. I'm not sure what else to add here, but the rate limit is being hit, and it's significantly impacting mass revert operations.

**Comment by mmd-osm** [comment]
The question was specifically about the API endpoints you're using.

**Comment by DavidKarlas** [comment]
I believe they are hitting on upload because https://github.com/zerebubuth/openstreetmap-cgimap/blob/5b5f18b6a6c76d198a59db1ddbfc8889fa14ba47/src/osm_diffresult_responder.cpp#L41
Which is responding with diffResult:
![image](https://github.com/zerebubuth/openstreetmap-cgimap/assets/774791/72919626-4ac5-43da-bafc-e04c7b120628)

**Comment by mmd-osm** [comment]
I'm not really sure that's the case. diffResult is a fairly small message, like mentioned earlier, that's about 100 bytes per object, if not less. Is DWG really reverting millions of objects?

**Comment by DavidKarlas** [comment]
From my test for 1000 objects uploaded it results in 54,255 bytes response size.

To put things into perspective(don't have DWG members numbers at hand) but todays [vandal ](https://www.openstreetmap.org/user/bojicat389) from first to last changeset it passed 25minutes in this time it modified 292370 nodes, 6739 ways and 1656 relations. 

Let's assume DWG member banned them and wants to revert it as fast as possible 300765 objects modified, so 300 * 54KB = 16MB. So it is very unlikely this is problem, unless production `--ratelimit` and `--maxdebt` are much smaller than defaults in code.

What is probably happening tool first fetches objects before doing revert, will take a look at [Thanos](https://github.com/Zaczero/Thanos) code...

**Comment by mmd-osm** [comment]
Thank you for double checking the numbers, much appreciated.

I'd like to mention one other topic which comes to mind. Assuming Thanos and osm-revert are all running on the same server, then even read-only API requests should use the authenticated user details, to avoid rate limiting based on IP address (rather than a single user). 

Zerebubuth had added this feature years ago: https://lists.openstreetmap.org/pipermail/dev/2016-October/029544.html

**Comment by DavidKarlas** [comment]
Looking at code it at [osm-revert/main.py#L188](https://github.com/Zaczero/osm-revert/blob/a64c94184d7f03cdb68595580ae0c3b51a068374/app/main.py#L188) as far as I understand requests are authenticated, but changeset that need reverting are downloaded, going back to our  [vandal](https://www.openstreetmap.org/user/bojicat389) from today... Downloading all changesets 76MB.

But I have now different theory, moderator jobs get really busy in this times, jumping between osm.org, JOSM, loading huge relations, kicked off osm-revert running at same time in background, all together, authenticated from multiple location hitting API from everywhere all at once, and boom, goes past the limit...

**Comment by SomeoneElseOSM** [comment]
>  but todays vandal

Just in case people are not aware - the revert of that isn't being done from a moderator account so is unrelated to this issue.

**Comment by mmd-osm** [comment]
@SomeoneElseOSM : today we're not (yet) differentiating between normal users and moderators when it comes to rate limiting. This is part of a new pull request by @DavidKarlas  only, which will get merged shortly.

**Comment by Zaczero** [comment]
> More specifically, I'm trying to find out if we're likely running into the issues mentioned here: [#294 (comment)](https://github.com/zerebubuth/openstreetmap-cgimap/pull/294#issuecomment-1783765703)
> 
> This is only feasible when we better understand how your tool works, what kind of API requests you're triggering, etc.

The osm-revert tool primarily retrieves changeset XML information from OSM. Element information is bulk-downloaded from Overpass. The only additional request involves creating and uploading the changesets.

**Comment by Zaczero** [comment]
> Looking at code at [osm-revert/main.py#L188](https://github.com/Zaczero/osm-revert/blob/a64c94184d7f03cdb68595580ae0c3b51a068374/app/main.py#L188) as far as I understand requests are authenticated, but changesets that need reverting are downloaded, going back to our [vandal](https://www.openstreetmap.org/user/bojicat389) from today... Downloading all changesets results in 76MB.
> 
> But I have now different theory, moderator job get really busy when vandals are active, jumping between osm.org, JOSM, loading huge relations, kicked off osm-revert running at same time in background, all together, authenticated from multiple locations hitting API from everywhere all at once, and boom, goes past the limit...

I have personally reverted some instances of mass-vandalism, and I have not performed any other actions on my account at the time. This issue appears to be isolated in this context.

**Comment by mmd-osm** [comment]
Thanks a lot for your feedback. Looking at the settings for cgimap in production ([link](https://github.com/openstreetmap/chef/blob/master/cookbooks/web/recipes/cgimap.rb#L44-L45)), a user would have to wait a bit more than 21 minutes, for a maxdebt of 250MB to be fully consumable again. So if you've downloaded e.g. some large changesets shortly before kicking off the revert job, chances are you're hitting the rate limiting more easily. 

So regarding our original problem I was trying to get some idea on: I think we should be good with 2-3GB maxdebt. If needed, we could bump the rate limit parameter as needed, to minimize any potential wait time for moderators.

**Comment by tomhughes** [comment]
The only thing we need here is the configuration options - what limit to set is an operational matter than can be adjusted as needed in response to observed conditions.

**Comment by mmd-osm** [comment]
You won't be able to set an arbitrarily high value from an operations point of view, but the max. limits in place should be still ok.

**Comment by mmd-osm** [comment]
@tomhughes : by the way, do we have memcached deployed on the dev instance at the moment? Could we run some tests there as well? How would we set up a moderator user there?

**Comment by tomhughes** [comment]
Yes it looks like the dev instances are using memcached and I can make people moderators.

**Comment by mmd-osm** [comment]
@tomhughes : sounds good. I have created a new user https://master.apis.dev.openstreetmap.org/user/mmd2mod to try out moderator rate limits.

@DavidKarlas , @Zaczero :  if you want to do a bit of testing with a "mod hat on",  please sign up on https://master.apis.dev.openstreetmap.org and post your user name in this issue.

A while time ago, I've uploaded a fair amount of data in Halifax, Nova Scotia, which could be used to test rate limiting: https://master.apis.dev.openstreetmap.org/#map=17/44.66416/-63.60977

**Comment by tomhughes** [comment]
I've made that user a moderator.

**Comment by DavidKarlas** [comment]
I tested it on my local machine few times, so I will pass chance to test on test server, @mmd-osm thank you for testing on separate system.
Btw, it might be a bit nicer/easier to test with https://github.com/zerebubuth/openstreetmap-cgimap/pull/295 merged

**Comment by mmd-osm** [comment]
I tested both scenarios on the dev instance. Results look good to me. I was having a bit of a hard time to hit the rate limit as a moderator, and even then, the retry-limit lasted a few secs only.

Also, including the Retry-Limit in the error message helps JOSM users to better understand what is going on, and how long they need to wait.

**Comment by DavidKarlas** [comment]
Thank you for testing this!

**Comment by mmd-osm** [comment]
@tomhughes : I've triggered a new ppa build process. Packages should be available soon, publication is still pending: https://launchpad.net/~mmd-osm/+archive/ubuntu/cgimap-809-jammy/+packages

**Comment by mmd-osm** [comment]
Change is in production now.

**Comment by DavidKarlas** [comment]
Yay, tested:
<img width="489" alt="image" src="https://github.com/zerebubuth/openstreetmap-cgimap/assets/774791/116776c5-163e-450b-83fa-7dff1fa97d23">
Thank you for all the support!

**Comment by DavidKarlas** [comment]
Now we just need someone from DWG to see if they have harder time hitting limits...

**Comment by SomeoneElseOSM** [comment]
>  someone from DWG someone from DWG

Thanks - [as I mentioned earlier](https://github.com/zerebubuth/openstreetmap-cgimap/issues/290#issuecomment-1783909253) I don't normally use a moderator account for reverts.  Some people do though, so we'll see what happens.

**Comment by DavidKarlas** [comment]
I assume adding moderator role to _revert accounts is big no-no?

**Comment by tomhughes** [comment]
I'm happy to add it to revert accounts of DWG members. I already added it to one of @woodpeck's repair accounts.
