### ISSUE TITLE
Add Retry-After http header in 509 response

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#291]
Error response could include some details about the expected wait time in seconds.
https://www.rfc-editor.org/rfc/rfc9110.html#name-retry-after

**Comment by DavidKarlas** [comment]
FYI, once https://github.com/zerebubuth/openstreetmap-cgimap/pull/294 is fixed I will open PR to fix this, here is commit: https://github.com/DavidKarlas/openstreetmap-cgimap/commit/64b5169f881dab786fee07d61de1169c3df6c8ef
