### ISSUE TITLE
Switch to api.openstreetmap.org API host

### ISSUE THREAD

**Issue by danieldegroot2** [zerebubuth/openstreetmap-cgimap#293]
Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`. ([api calls](https://github.com/search?q=repo%3Azerebubuth%2Fopenstreetmap-cgimap%20www.openstreetmap.org%2Fapi&type=code))

However, these are test files, so I am not sure if the change is needed.

(Is: https://github.com/openstreetmap/operations/issues/951)

**Comment by mmd-osm** [comment]
This change is not needed, it's an http header in some test code, that could be just some random string.
