### ISSUE TITLE
Compatibility with libpqxx 7.x.x

### ISSUE THREAD

**Issue by Woazboat** [zerebubuth/openstreetmap-cgimap#299]
libpqxx has changed quite a bit with version 7.x.x and above that makes it currently incompatible with cgimap

https://github.com/jtv/libpqxx/blob/master/NEWS

I've made a few changes that allow it to compile again here:
https://github.com/zerebubuth/openstreetmap-cgimap/compare/master...Woazboat:openstreetmap-cgimap:libpqxx-7-compatibility

Unfortunately that's not quite enough to allow cgimap to function properly again. 
Currently, almost all prepared SQL statements are defined directly in the functions that call them and they are redefined with every call. 

e.g.

```C++
int readonly_pgsql_selection::select_nodes(const std::vector<osm_nwr_id_t> &ids) {
  if (ids.empty())
    return 0;

  m.prepare("select_nodes", "SELECT id FROM current_nodes WHERE id = ANY($1)");

  return insert_results(m.exec_prepared("select_nodes", ids), sel_nodes);
}
```

In libpqxx 6.x this worked 'fine', however with libpqxx 7.x a redefinition of a prepared statement with the same identifier now causes an exception. This needs to be changed across the board so that all prepared statements are defined once only at the beginning and aren't redefined with every function call.

(Even if this didn't cause an error, it should be changed purely for performance reasons as redefining all prepared statements with every function call is unnecessary.)

**Comment by mmd-osm** [comment]
The way this works in libpqxx 6.x is that they’re using some caching and only prepare statements once, even if you call prepare multiple times. From your description it seems this caching is no longer available. Since we’re calling our own wrapper of prepare we could simply add that bit there, rather than changing everything.

**Comment by mmd-osm** [comment]
The issues with prepare statements no longer occur now, and there are only two failing test cases left.

We used to have some issues with escaping in libpqxx in the past. Looks like this is showing up again in the new version.

tags{""comment"" => ""Just adding some streetnames"", ""created_by"" => ""JOSM 1.61"", }

vs.

tags{"comment" => "Just adding some streetnames", "created_by" => "JOSM 1.61", },



```
FAIL: test/test_apidb_backend_changesets
========================================

Creating new PostgreSQL cluster 16/regress ...
Error: Expecting changeset 500 to be equal, but changeset(changeset_info(id=500, created_at="2023-11-08T18:12:39Z", closed_at="2023-11-08T19:12:39Z", uid=31, display_name="demo", bounding_box=bbox(0, 0, 0, 0), num_changes=0, comments_count=0), tags{""comment"" => ""Just adding some streetnames"", ""created_by"" => ""JOSM 1.61"", }, include_comments=0, comments[], time=2023-11-08T18:12:39+0000) != changeset(changeset_info(id=500, created_at="2023-11-08T18:12:39Z", closed_at="2023-11-08T19:12:39Z", uid=31, display_name="demo", bounding_box=bbox(0, 0, 0, 0), num_changes=0, comments_count=0), tags{"comment" => "Just adding some streetnames", "created_by" => "JOSM 1.61", }, include_comments=0, comments[], time=2023-11-08T18:12:39+0000)


FAIL: test/test_apidb_backend_changeset_uploads
===============================================

Creating new PostgreSQL cluster 16/regress ...
Error: Expecting first node written to be equal, but node(element_info(id=1, version=1, changeset=1, timestamp=2023-11-08T18:12:46Z, uid=1, display_name=user_1, visible=1), lon=131.033, lat=-25.3449, tags{"name" => "Uluṟu", "ele" => "863", }) != node(element_info(id=1, version=1, changeset=1, timestamp=2023-11-08T18:12:46Z, uid=1, display_name=user_1, visible=1), lon=131.033, lat=-25.3449, tags{""ele"" => ""863"", ""name"" => ""Uluṟu"", }), in update
```

**Comment by Woazboat** [comment]
Thanks for fixing this!

I still get some linker errors when I try to run `make check`. I had to change the build system to also link in libpqxx for some more of the tests: https://github.com/zerebubuth/openstreetmap-cgimap/commit/2a8a7b6eff8df2e670d8b15c81f19027111a80b0

```
make check

Making check in src
make[1]: Entering directory '/home/user/openstreetmap-cgimap/src'
make  ../test/test_core ../test/test_apidb_backend_nodes ../test/test_apidb_backend_oauth ../test/test_apidb_backend_oauth2 ../test/test_apidb_backend_historic ../test/test_apidb_backend_changesets ../test/test_apidb_backend_changeset_downloads ../test/test_apidb_backend_changeset_uploads ../test/test_parse_id_list ../test/test_basicauth ../test/test_oauth ../test/test_oauth2 ../test/test_http ../test/test_parse_time ../test/test_parse_osmchange_input ../test/test_parse_changeset_input
make[2]: Entering directory '/home/user/openstreetmap-cgimap/src'
  CXXLD    ../test/test_core
/usr/bin/ld: ../test/test_core.o: in function `_GLOBAL__sub_I__Z12read_headersRSiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
/usr/include/pqxx/strconv.hxx:82:(.text.startup+0x24): undefined reference to `pqxx::internal::demangle_type_name[abi:cxx11](char const*)'
/usr/bin/ld: ../test/test_core.o: in function `__static_initialization_and_destruction_0':
/usr/include/pqxx/strconv.hxx:82:(.text.startup+0x48): undefined reference to `pqxx::internal::demangle_type_name[abi:cxx11](char const*)'
/usr/bin/ld: /usr/include/pqxx/strconv.hxx:82:(.text.startup+0x87): undefined reference to `pqxx::internal::demangle_type_name[abi:cxx11](char const*)'
/usr/bin/ld: /usr/include/pqxx/strconv.hxx:82:(.text.startup+0xab): undefined reference to `pqxx::internal::demangle_type_name[abi:cxx11](char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1289: ../test/test_core] Error 1
```

**Comment by mmd-osm** [comment]
I've seen this change in your commit, but cannot reproduce here (also see the Github actions log file). Which environment does this happen in?

**Comment by Woazboat** [comment]
I'm running debian testing. Not sure why that would lead to different libraries being linked in.

|package|version|
| --- | --- |
|g++|4:13.2.0-1|
|libpqxx-dev| 7.8.1-2|
|libxml2-dev| 2.9.14+dfsg-1.3|
|libfcgi-dev| 2.4.2-2|
|zlib1g-dev| 1:1.2.13.dfsg-3|
|libboost-dev| 1.74.0.3|
|libboost-program-options-dev| 1.74.0.3|
|libfmt-dev| 9.1.0+ds1-2|
|libmemcached-dev| 1.1.4-1|
|libcrypto++-dev| 8.9.0-1|
|libargon2-dev| 0~20190702+dfsg-4|
|libyajl-dev| 2.1.0-5|

**Comment by mmd-osm** [comment]
I'm using  `--enable-static --disable-shared` as configure options in my Dockerfile, although for some issues with fmt. Not sure if this might have some impact here: https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/Dockerfile_trixie#L23

**Comment by Woazboat** [comment]
Ah, yes I think the static linking would explain that. When I compile it without the build system changes but with static linking it works. With the linker changes it works for both dynamic and static linking.
