### ISSUE TITLE
Follow up on OpenHistoricalMap issue

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#330]
Context: https://github.com/OpenHistoricalMap/issues/issues/642

Not running in daemon mode:
* cgimap binary starting up as a single process, handling one user at a time only.
* Not meant to be run in standalone mode: needs to be managed by supervisord or lighttpd, to ensure proper restarts in case of failure, and more importantly, start up multiple processes.
* CGImap  exits with non-zero return code in case of error.
* Remove parameter "--instances=30" in Dockerfile, since it's only relevant in daemon mode.
* Maybe add warning message during startup in this case.

Running in daemon mode:
* Automated restarting of forked processes works ok in case of database error.

Overall:
* Improve documentation, clarify how daemon / non-daemon modes behave.

**Comment by Rub21** [comment]
Good points to consider, thank you!
