### ISSUE TITLE
test_parse_id_list failure on ARM64

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#345]
For some reason, I'm seeing unit test failures for test_parse_id_list on my Raspberry running bookworm in 64bit mode.  I'm not exactly sure what's going on, just posting it here so we don't forget about it.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_parse_id_list is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
Invalid string
-------------------------------------------------------------------------------
../test/test_parse_id_list.cpp:35
...............................................................................

../test/test_parse_id_list.cpp:36: FAILED:
  CHECK( api06::valid_string("foobar\x80") == false )
with expansion:
  true == false

../test/test_parse_id_list.cpp:37: FAILED:
  CHECK( api06::valid_string("foobar\xff") == false )
with expansion:
  true == false

-------------------------------------------------------------------------------
Id list with garbage
-------------------------------------------------------------------------------
../test/test_parse_id_list.cpp:66
...............................................................................

../test/test_parse_id_list.cpp:70: FAILED:
  CHECK( result.empty() == true )
with expansion:
  false == true

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It's the only test failure by the way, everything else works ok:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
============================================================================
Testsuite summary for CGImap 0.8.10
============================================================================
# TOTAL: 33
# PASS:  32
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mmd-osm** [comment]
x86_64: https://cpp.godbolt.org/z/chx53h6zd -> ok
ARM64: https://cpp.godbolt.org/z/zEWKxnGPE -> fails

**Comment by Woazboat** [comment]
Looks like the compiler optimizes the check `c >= 0 && c <= UCHAR_MAX` to constant `true` because `char` == `unsigned char`. If you replace the `char` parameter in the lambda with `signed char` it works.

https://cpp.godbolt.org/z/fb9nfd59P

**Comment by tomhughes** [comment]
Don't forget `char` may default to signed on some platforms and unsigned on others - it is implementation defined.

**Comment by Woazboat** [comment]
Yup, usually signed for x86, unsigned for arm.

**Comment by mmd-osm** [comment]
Maybe it would be easier to whitelist all permitted characters, i.e. as space, digits 0-9, comma, and v for version.

```c++
constexpr bool valid_string(std::string_view str)
{
  return str.find_first_not_of(" 0123456789,v") == std::string::npos;
}
```

**Comment by Woazboat** [comment]
That is going to be far slower than the simple range check and is duplicated effort with the parsing that happens later

**Comment by mmd-osm** [comment]
Yes, somehow the boost based parser is doing some `BOOST_ASSERT(strict_ischar(ch))`, which might terminate the program with an assertion failure depending on NDEBUG and user input. In the end I decided to add the additional check, and leave the rest as is.

For the sake of parsing a list of objects with an optional version number, using boost might be a bit overkill. It was already in place when I started here.

**Comment by Woazboat** [comment]
We could simply check if only the 7 least significant bits are used (i.e. isascii). That would be just as fast (potentially even faster?) and should work everywhere.
```C++
bool isascii(char ch)
{
    return 0 == (ch & ~0x7f);
}
```

**Comment by mmd-osm** [comment]
Right, both versions generate the same assembly code (not eax; shr al,7) -> https://cpp.godbolt.org/z/MrjK773fW
For some reason, I find the version without two's complement better.

**Comment by mmd-osm** [comment]
Tests on ARM64 are passing again:
```

============================================================================
Testsuite summary for CGImap 0.8.10
============================================================================
# TOTAL: 33
# PASS:  33
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
