### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by Woazboat** [zerebubuth/openstreetmap-cgimap#393]
> The api.osm.org instance runs CGImap as a daemon and Apache with [mod_fastcgi_handler](https://github.com/hollow/mod_fastcgi_handler).

The page https://github.com/hollow/mod_fastcgi_handler does not exist (anymore)

**Comment by mmd-osm** [comment]
This seems outdated anyway, chef repo is using the proxy_fcgi apache module today: https://github.com/openstreetmap/chef/blob/237d93489bca6fbae88dd2a9f63fedca0aba0a36/cookbooks/web/recipes/frontend.rb#L34

So maybe replace the link by `https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html`
