### ISSUE TITLE
Deprecate support for Ubuntu 20.04

### ISSUE THREAD

**Issue by Woazboat** [zerebubuth/openstreetmap-cgimap#404]
The openstreetmap-website db now requires at least postgresql version 13 (https://github.com/openstreetmap/openstreetmap-website/pull/4405). Ubuntu 20.04 only ships postgresql version 12 and is therefore unable to run the openstreetmap api stack. While cgimap _could_ be run on Ubuntu 20.04 on a separate host, it doesn't make much sense to support it further.

**Comment by mmd-osm** [comment]
https://github.com/openstreetmap/openstreetmap-website/pull/4484 doesn't even mention Ubuntu 20.04 anymore, although it's still supported for another year. While we could switch to https://www.postgresql.org/download/linux/ubuntu/ provided PPAs and still run Postgresql 13 on Ubuntu 20.04 (https://github.com/mmd-osm/openstreetmap-cgimap/tree/patch/ubuntu2004pg13), it's probably not worth the hassle.

Ok to deprecate it.
