### ISSUE TITLE
Add the ability to limit changeset size (CGImap integration)

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#412]
Tracking issue for integration of https://github.com/openstreetmap/openstreetmap-website/pull/4908 into CGImap.

We can now start working on CGImap based on this implementation. As a reminder, the code should roughly follow our previous changeset size limit approach, as explained in https://github.com/zerebubuth/openstreetmap-cgimap/pull/409#issuecomment-2171805476

New code should be implemented against the master branch and will be backported later to 0.9.x. Backporting the new code means: we will create a new branch "release/0.9.3" with the added bounding box check. This branch is based on https://github.com/zerebubuth/openstreetmap-cgimap/tree/release/0.9.2 

Related discussion: https://github.com/zerebubuth/openstreetmap-cgimap/pull/409

**Comment by mmd-osm** [comment]
The database function returns a size information only, which means we would have this on CGImap as well. Started a follow up discussion in https://github.com/openstreetmap/openstreetmap-website/pull/4908 to see if we could pass {min,max}_{lat,lon} paramters to the database function instead, and the db function do the rest for us.

**Comment by tomhughes** [comment]
I don't want to have to call the database functions hundreds of times though, which is why the rails code is careful to only call it once for each instance of the changeset model.

**Comment by mmd-osm** [comment]
Well, we would also only call it once shortly before upload processing has finished and we're committing the changes. So from CGImap side, adding these additional four parameters would have no impact on how often we're calling the db function. Would this be different on Rails?

**Comment by mmd-osm** [comment]
Before I forget it, there may also be cases where we don't have a valid bounding box at all, and the db function should  skip the size calculation.

**Comment by mmd-osm** [comment]
(Please ignore previous post, if we don't have a valid bounding box, we will not call the db function at all)

**Comment by tomhughes** [comment]
Sure I'll just spend another evening on this to re-engineer everything. Next week maybe?

**Comment by mmd-osm** [comment]
Sure, we can go ahead with the current db function interface and revisit the topic next week.

**Comment by mmd-osm** [comment]
First test in JOSM:

![image](https://github.com/zerebubuth/openstreetmap-cgimap/assets/5842757/2846f5d8-3315-4831-bd31-88f009b3d153)

**Comment by talllguy** [comment]
@mmd-osm how does it look in iD for that test?

**Comment by simonpoole** [comment]
1st reaction: 
- we don't return 413 anywhere except for the user pref api currently (and I suspect that most editors don't use that) at least not documented and this may lead to breakage.
- the error text is too verbose, just return something like "Changeset bounding box size limit exceeded" ("blocked" has negative associations).

Will test in a couple of minutes.

**Comment by mmd-osm** [comment]
@simonpoole : no unfortuantely, it's only available on my local machine for testing. Once I merge the PR into master, and Tom enables the new parameter, it's available for testing on the dev instance.

**Comment by mmd-osm** [comment]
@talllguy  Here's what it looks like in iD

![image](https://github.com/zerebubuth/openstreetmap-cgimap/assets/5842757/360709ab-408f-4a34-b582-d0168c1d84eb)

**Comment by mmd-osm** [comment]
#### Everyone can start testing now on https://master.apis.dev.openstreetmap.org

**Comment by simonpoole** [comment]
worksforme. though even on with an account with nearly no edits I had to create a 6'000 km way to trigger the limit.

**Comment by mmd-osm** [comment]
@simonpoole : I'm not sure I'm following you. I can see a changeset by SimonDev2 https://master.apis.dev.openstreetmap.org/user/SimonDev2/history that has a 5x5m bounding box. The other large bbox was created by SimonDev (who is around since 1872 and allowed to create much larger bboxes).

When reporting issues, it would be good if you could state the exact objects you're referring to, and the expected and actual behavior.

**Comment by simonpoole** [comment]
The 1st is the end node of https://master.apis.dev.openstreetmap.org/way/430652173i for which I respectfully suggest that the bounding box should be larger than 5mx5m.

**Comment by simonpoole** [comment]
The 5m X 5m changeset was moving the end node of https://master.apis.dev.openstreetmap.org/changeset/368990 which I created with SimonDev which didn't trigger the limit.

**Comment by mmd-osm** [comment]
@simonpoole : so regarding the bbox, I checked this scenario on the Rails port, and it's behaving exactly the same way as in CGImap. This kind of change doesn't take the length of the whole way into account, but only the previous and current node locations. Since we haven't changed the definition of how we're calculating bounding boxes, we would end up with a very small bbox, which is permitted also for very new users.

**Comment by simonpoole** [comment]
That isn't the issue. Creating the way in the 1st place didn't trigger the limit is an issue.

**Comment by simonpoole** [comment]
That isn't the issue. Creating the way in the 1st place didn't trigger the limit is an issue.

But even considering that, not calculating the bounding box on the complete element allows inching positions as an avenue for vandals to work around the limit and imho should be treated different.

PS: the github mobile App is paying up a bit, sorry for any duplicate comments.

**Comment by Woazboat** [comment]
That would require 1) recursing up to find all objects that have an edited object as a member and then 2) recursing down to all nodes of objects found in step 1) to calculate the bounding box over all of those.
That's a fairly expensive operation and would require a lot more changes to the code than what we have now.

**Comment by mmd-osm** [comment]
Well I tend to agree that the current bbox calculation is not a very good approximation of expected tile re-rendering costs.

**Comment by Woazboat** [comment]
It's neither very good for figuring out the affected are for rendering nor for users to figure out what actually changed where.

**Comment by mmd-osm** [comment]
I think it would be interesting to know what the maximum damage to real OSM data would be like in this scenario.

Most ways are probably not spanning the whole globe, and likewise the distance between two way nodes should not be thousands of kilometers. Even if so, we could possibly mitigate the issue by introducing additional supporting points, split the way or something similar.

**Comment by mmd-osm** [comment]
@tomhughes : I have released 0.9.3 in the meantime: https://github.com/zerebubuth/openstreetmap-cgimap/releases/tag/v0.9.3

PPA build was successful, publishing should be finished very soon: https://launchpad.net/~mmd-osm/+archive/ubuntu/cgimap-903-jammy

**Comment by mmd-osm** [comment]
By the way, JOSM clears the undo buffer during upload. In case the upload fails, there's no way for a user to undo some changes to the point that the bbox is small enough again. Fun times ahead.

**Comment by simonpoole** [comment]
> By the way, JOSM clears the undo buffer during upload. In case the upload fails, there's no way for a user to undo some changes to the point that the bbox is small enough again. Fun times ahead.

Don't see the issue here, both Vespucci and JOSM allow selective uploads and you can use filter expressions to select changes in an appropriate bounding box.

**Comment by mmd-osm** [comment]
Ok, that's good to know. I haven't explored all these options in detail yet. I suppose we will see new users fairly soon who need some help rescuing their edits.

**Comment by AntonKhorev** [comment]
It won't be easy to select deleted elements for upload.

**Comment by simonpoole** [comment]
> It won't be easy to select deleted elements for upload.

With the filter expressions that shouldn't be an issue (just started supporting that in Vespucci two weeks ago https://github.com/MarcusWolschon/osmeditor4android/pull/2574).
