### ISSUE TITLE
Sub-optimal viability checks.

### ISSUE THREAD

**Issue by pnorman** [zerebubuth/openstreetmap-cgimap#70]
_This example is with the `/api/0.6/node/id#` call, but it equally applies to any single- or multi-element fetch and applies to parts of calls which join through `way_nodes` or `relation_members`, but in a more complex way._

The nodes call does this approximately

``` c++
if (sel.select_nodes(ids) == 0) {
  throw http::not_found("");
} else {
  if (sel.check_node_visibility(id) == data_selection::deleted) {
    throw http::gone(); // TODO: fix error message / throw structure 
                        // to emit better error message
  }
}
/* XML serialization code */
formatter.start_element_type(element_type_node);
w.prepared("extract_nodes").exec();
/* Tags stuff */
```

For the common case of a node that exists, the SQL results in
- For `sel.select_nodes(ids)`, an index scan (_scan A_) on `current_nodes`, inserting the id into `tmp_nodes` and optionally an anti-join against `tmp_nodes`.
- For `sel.check_node_visibility(id)`, an index scan (_scan B_) on `current_nodes`, returning `visibility`
- For `w.prepared("extract_nodes").exec();`, an index scan (_scan C_) on `current_nodes`, returning the full node information.

In the case of `/api/0.6/node/id#`, index scans A, B and C are on the primary key (`id`). In the case of `/api/0.6/map` index scan A is with the tile index while B and C are still on `id`.

All **three** index scans fetch the same rows. Although the rows will be in memory cache, this is sub-optimal.

I propose the following
1. Have a precondition that `check_node_visibility(id)` is only called on on IDs that have been added to `tmp_nodes`. In practice, this is true - we only ever get IDs from query or from the table itself. In the former case, the first thing we do is add the id to the table. In the latter, it is obviously in `tmp_nodes` if we got it from selecting from `tmp_nodes`. No code changes are required for this.
2. Change the definition of `tmp_nodes` to be virtually identical to `current_nodes`. I don't think we'd need `tile` in `tmp_nodes`, but otherwise I think they'd be the same.
3. Populate all the columns of `tmp_nodes`. For `/api/0.6/node/id#` this just changes what is being selected from the query. For `/api/0.6/map` it involves another JOIN, but it involves no more index scans or fetching from `current_nodes` then we'd otherwise have.
4. Have `check_node_visibility(id)` select from `tmp_nodes`. This is the reason for 1.
5. Have `w.prepared("extract_nodes").exec();` not join against `current_nodes` but just retrieve the data from `tmp_nodes`.

This would eliminate two index scans in the case of single- and multi-element fetch calls and eliminate one from map calls (which have one less already, approximately).

This is basically what I did for pgsnapshot.

I can think of more efficient ways to do this using `RETURNING` of the `INSERT` statement that would allow XML for nodes to be started _while_ the various joins with `current_way_nodes` are still being executed, but they're above my C++ skills, and what I propose should be a noticeable improvement.

Edit: Updated to remove num_nodes() and the related sequential scan.

**Comment by mmd-osm** [comment]
@pnorman : I'm not quite sure on the status of this issue. Was this implemented already way back then and we can close it, or is there anything left to do?

**Comment by pnorman** [comment]
I'm not sure without research

**Comment by mmd-osm** [comment]
Thanks, appreciate your feedback. There's really no immediate need to spend much time on this issue.

I thought, maybe you remember what the status was, and we can just close it in case it is no longer relevant. We'll just leave it as is now.

**Comment by mmd-osm** [comment]
I'm closing this one, as the discussion seems to be relevant for temporary tables tmp_* (write backend) and pgsnapshot backend only, both of which have been removed in the meantime.
