### ISSUE TITLE
Sorting by ID within object types

### ISSUE THREAD

**Issue by pnorman** [zerebubuth/openstreetmap-cgimap#88]
Currently the apidb (and probably other) backend(s) do not produce output that is type then ID sorted, only output that is type sorted.

This arose in the context of openstreetmap/osm2pgsql#151, which may be an osm2pgsql bug, but there are a few tools that expect (type,id) sorting. If it has a negligible impact on performance, I'd just as soon sort all output for flexibility of use. If it does have a performance impact, I'm not as sure.

I know that we refer people to planet files and extracts, but it's nice to simple be able to use the results of a `map` or `[way|relation]/full` call in standard tools.

The relevant code for readable apidb is in [writable_pgsql_selection.cpp](https://github.com/zerebubuth/openstreetmap-cgimap/blob/6350fee6113318edd2c4027b9d16b0d52d2d9649/src/backend/apidb/writeable_pgsql_selection.cpp#L380-L395) and reproduced below for the case of nodes.

``` sql
SELECT n.id, n.latitude, n.longitude, n.visible, 
    to_char(n.timestamp,'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') AS timestamp, 
    n.changeset_id, n.version 
  FROM current_nodes n 
    JOIN tmp_nodes tn ON n.id = tn.id
```

The obvious change is an `ORDER BY n.id`. This should change the query plan by taking the existing plan and performing a sort on the results. Given that we're constrained that COUNT(*) on tmp_nodes does not exceed ~75k-100k on map calls, the sort should be an in-memory sort and fairly fast.

What it might impact is the time for the first row. Given that we're not using cursors, it's not an issue right now, but #71 raises the possibility of switching to them.

Thoughts? I can try to run some benchmarks at home, I **believe** they'll be valid. And of course there's the readonly apidb too.

**Comment by Komzpa** [comment]
For some idea of load imposed by sorting, osm2pgsql database behind mapnik is using a lot of ORDER BY in queries, and that does not cause a performance issue there: 

https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml - ctrl+f - "order by"

For understanding why and how it works fast, there's a presentation from pgconf:
https://wiki.postgresql.org/images/5/59/Sorting_through_the_ages.pdf

**Comment by mmd-osm** [comment]
There's no sorting on the Rails port either (see https://www.openstreetmap.org/api/0.6/map.xml?bbox=-74.81825%2C40.5824%2C-74.81415%2C40.58383 as an example). I'm inclined to close this issue, unless someone also creates an issue for the Rails ports to keep them both in sync.

**Comment by pnorman** [comment]
I thought the rails port did, but if it doesn't this can be closed.

**Comment by mmd-osm** [comment]
Thanks for the quick feedback. I'll close this issue then.
