### ISSUE TITLE
Nodes missing from export of way

### ISSUE THREAD

**Issue by cbdavis** [zerebubuth/openstreetmap-cgimap#89]
When I go to pages such as http://www.openstreetmap.org/way/180296516 and http://www.openstreetmap.org/way/238933033, and then click on "download as as an xml" at the bottom of the page, some of nodes in the way are missing from the data export.  

Loading the data into JOSM doesn't display anything, although there are warnings such as this: "INFO: Way 180,296,516 with 141 nodes has incomplete nodes because at least one node was missing in the loaded data."

In the XML, I see that the generator of the data is "CGImap 0.3.3 (23653 thorn-02.openstreetmap.org)", which seems to be the latest version on github.  I'm seeing the same behaviour as well with osmfilter (http://wiki.openstreetmap.org/wiki/Talk:Osmfilter#Force_dependencies)

Is this a known issue or a weird mapping relationship that is causing not all of the nodes to be exported?

Best regards,

Chris

**Comment by zerebubuth** [comment]
Sorry, this is really old... I'm guessing this isn't still an issue - if it is, please re-open.
