### ISSUE TITLE
Build error boost_system

### ISSUE THREAD

**Issue by tigerss** [zerebubuth/openstreetmap-cgimap#93]
Hello, I don't know why I'm getting this error. I'm on Ubuntu 14.04 64bit.
The error I'm getting:

root@maps:~/src/openstreetmap-cgimap# make
Making all in src
make[1]: Entering directory `/root/src/openstreetmap-cgimap/src'
  CXXLD    ../map
backend.o: In function `boost::thread_exception::thread_exception(int, char const*)':
/usr/include/boost/thread/exceptions.hpp:51: undefined reference to `boost::system::system_category()'
backend.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:224: undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
make[1]: *** [../map] Error 1
make[1]: Leaving directory `/root/src/openstreetmap-cgimap/src'
make: *** [all-recursive] Error 1

**Comment by zerebubuth** [comment]
Yes, that looks like a problem. Thanks for reporting it. So that I can investigate the cause of the error, could you post (as a gist, on pastebin, wherever) the file `config.log` which was created when you ran `./configure`, please?

**Comment by tigerss** [comment]
Thanks for the fast response! 
Here it is the [config.log](http://pastebin.com/N0q5NXqY)

**Comment by zerebubuth** [comment]
Looks like the issue was that the docs didn't mention `libboost-system-dev` as a required package, and the build system didn't check that the library was present (it checked the headers, but continued despite the library not being found). I have just pushed some commits which should fix this. Please could you try them and let me know if that fixes the issue for you?

**Comment by tigerss** [comment]
This is working for me, thank you!
