### ISSUE TITLE
Asking for a node multiple times incorrectly reports a missing node

### ISSUE THREAD

**Issue by tomhughes** [zerebubuth/openstreetmap-cgimap#94]
If you give cgimap a nodes query that requests the same node more than once then it will fail and claim that a requested node is missing. So, for example this query:

```
/api/0.6/nodes?nodes=1,2,2,3
```

will (unlike the rails version) return 404 even though all three nodes exist. The cause is https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/api06/nodes_handler.cpp#L18 which compares the number of nodes returned by the select with the number of IDs requested to try and detect missing nodes.

This actually broke iD (https://github.com/openstreetmap/iD/issues/2626) although that has now been fixed by changing iD to dedupe the request.

**Comment by tomhughes** [comment]
I'm guessing this probably affects the other multiple object calls.

**Comment by bhousel** [comment]
Thanks Tom for opening the issue...
