### ISSUE TITLE
inject

### ISSUE THREAD

**Issue by curl6425** [zerebubuth/openstreetmap-cgimap#99]

**Comment by zerebubuth** [comment]
I don't understand what you mean by creating an issue with the title "inject" and no description. Please could you provide more details of what the problem is, including as much detail as possible and preferably with steps to reproduce and/or a test case?

**Comment by curl6425** [comment]
hi 


im sorry im newbie here im experementing how get the product details  such cellphones  etc

im trying to get purchase owners name searching info location and status of a apple device and android via imei or serial...

thank you so much
